version: '3.9'

services:
    postgres:
        container_name: smart-toilet
        image: postgres:12-alpine 
        # automatic restarts the container 
        restart: always
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: tebasmart_development
            TZ: 'GMT+8'
            PGTZ: 'GMT+8'
        volumes: 
            - postgres:/var/lib/postgresql/data
        ports: 
            - "5432:5432"
        networks:
            - postgres




    pgadmin:
        container_name: pgadmin4
        image: dpage/pgadmin4
        # automatic restarts the container 
        restart: always
        environment: 
            PGADMIN_DEFAULT_EMAIL: admin@gmail.com
            PGADMIN_DEFAULT_PASSWORD: SuperSecret
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes: 
            - pgadmin:/root/.pgadmin
    
        # pgadmin listen port 80....
        ports: 
            - "5050:80"
        networks:
            - postgres

            
     

networks:
    postgres:
        driver: bridge

volumes:
    postgres:
    pgadmin:


