version: '3.1'

services:
    postgres:
        container_name: postgres_db
        image: postgres 
        # automatic restarts the container 
        restart: always
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /data/postgres
        volumes: 
            - postgres:/data/postgres
        ports: 
            - "5431:5432"
        networks:
            - postgres




    pgadmin:
        container_name: pgadmin4
        image: dpage/pgadmin4
        # automatic restarts the container 
        restart: always
        environment: 
            PGADMIN_DEFAULT_EMAIL: admin@gmail.com
            PGADMIN_DEFAULT_PASSWORD: SuperSecret
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes: 
            - pgadmin:/root/.pgadmin
    
        # pgadmin listen port 80....
        ports: 
            - "5050:80"
        networks:
            - postgres

            
     

networks:
    postgres:
        driver: bridge

volumes:
    datapostgres:
    pgadmin:


